matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
language: php
dist: trusty
php:
 - '5.2'
 - '5.3'
 - '5.4'
 - '5.5'
 - '5.6'
 - '7.0'
 - nightly
script: php utils/test.php && php utils/ootest.php && php utils/other-tests.php
